# Generated by Django 4.2 on 2024-04-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categoria_parent_alter_producte_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='shop.categoria'),
        ),
    ]
