# Generated by Django 4.2 on 2024-04-04 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_categoria_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cistella',
            options={'verbose_name_plural': 'Cistelles'},
        ),
        migrations.RemoveField(
            model_name='cistella',
            name='producte',
        ),
        migrations.RemoveField(
            model_name='cistella',
            name='quantitat',
        ),
        migrations.CreateModel(
            name='CistellaProducte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField(default=1)),
                ('cistella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cistella')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.producte')),
            ],
        ),
        migrations.AddField(
            model_name='cistella',
            name='productes',
            field=models.ManyToManyField(through='shop.CistellaProducte', to='shop.producte'),
        ),
    ]
