# Generated by Django 4.2 on 2024-04-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cistella_options_remove_cistella_producte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallcompra',
            name='preu_unitari',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
