# Generated by Django 4.2 on 2024-04-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_detallcompra_preu_unitari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallcompra',
            name='preu_unitari',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
